name: Hosting Preview

on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - feature/**
      - bugfix/**

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm ci
          npm run build
          # Angular build -> dist/<project-name>, ensure "outputPath" in angular.json matches.
          npx cap sync # keep native in sync (optional for hosting)

      - name: Setup Firebase token from service account
        id: fbtoken
        uses: w9jds/firebase-action@v13
        with:
          args: apps:list
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Deploy preview channel for this branch
        uses: w9jds/firebase-action@v13
        with:
          args: hosting:channel:deploy ${{ github.ref_name }} --expires 7d --project ${{ secrets.FIREBASE_PROJECT_ID }} --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Output preview URL
        run: echo "Preview deployed for ${{ github.ref_name }}"
