name: Android CI (Build & Distribute)

on:
  push:
    branches: [ main, develop, release/** ]
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps & build web (Ionic/Angular)
        run: |
          npm ci
          npm run build
          npx cap sync android

      - name: Set up Java (Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Decode keystore
        working-directory: android
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > release.keystore

      - name: Set signing properties
        working-directory: android
        run: |
          cat <<EOF >> gradle.properties
          MYAPP_UPLOAD_STORE_FILE=release.keystore
          MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }}
          MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}
          EOF

      # Ensure android/app/build.gradle uses the props above in signingConfigs.release

      - name: Build AAB (release)
        working-directory: android
        run: ./gradlew --no-daemon bundleRelease

      - name: Locate artifact
        id: paths
        run: |
          echo "AAB=$(find android/app/build/outputs/bundle/release -name '*.aab' | head -n1)" >> $GITHUB_OUTPUT
          echo "APK=$(find android/app/build/outputs/apk/release -name '*.apk' | head -n1 || true)" >> $GITHUB_OUTPUT
          echo "Found AAB: $(cat $GITHUB_OUTPUT | sed -n 's/^AAB=//p')"

      - name: Upload artifact (optional)
        if: ${{ steps.paths.outputs.AAB != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: ${{ steps.paths.outputs.AAB }}

      - name: Distribute to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          file: ${{ steps.paths.outputs.AAB }}
          groups: ${{ secrets.APP_DIST_GROUPS }}
          releaseNotes: "CI build from ${{ github.ref_name }} – ${{ github.sha }}"
